# Debug == 0
# Others.. I don't know.
log-level: 2

# Extension settings.
extensions:
  mythicmobs:
    enabled: false

    # Any mythic mobs spawn inside arena but ain't a mob of arena will be removed
    block-non-arena-mythic-mob: true
  placeholderapi:
    enabled: false
  discordsrv:
    enabled: false
  macommands:
    enabled: true

    commands:
      start:
        - 'say Hello world!'
      end:
        - 'say Bye world!'