# Debug == 0
# Others.. I don't know.
log-level: 2

# Extension settings.
extensions:
  mythicmobs:
    enabled: false

    # Reload MobArena arena handler after initializing new creatures.
    reload-arena-master: true

    # Any mythic mobs spawn inside arena but ain't a mob of arena will be removed
    block-non-arena-mythic-mob: true
  placeholderapi:
    enabled: false
  discordsrv:
    enabled: false
  macommands:
    enabled: false

    commands:
      start:
        - 'say Hello %arena%!'
      player-join:
        - 'say %player% joined %arena%'
      player-leave:
        - 'say %player% left %arena%'
      player-ready:
        - 'say %player% is ready in %arena%'
      kill:
        - 'say %player% kill a mob!'
      player-death:
        - 'say %player% died...'
      complete:
        - 'say %arena% finished. (survivors: %survivor_count%)'
      end:
        - 'say Bye %arena%...'