name: ${project.name}
version: ${project.version}
author: Sait
main: me.sait.mobarena.extension.MobArenaExtensionPlugin
depend:
  - MobArena
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - DiscordSRV
commands:
  mobarenaextension:
    aliases: [mae, arenaextension, mobarenaextensions]
    description: Main plugin command